version: '3.8'

services:
  # Nginx reverse proxy with SSL support
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl  # Mount SSL certificates
    depends_on:
      - key-service
      - data-service
      - upload-service
    restart: unless-stopped

  # PostgreSQL with persistent storage
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backups:/backups  # Backup mount point
    restart: unless-stopped
    # Don't expose port in production for security

  # Key service - scaled for high availability
  key-service:
    build: ./key-service
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=production
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    restart: unless-stopped
    depends_on:
      - postgres

  # Data service - scaled for high throughput
  data-service:
    build: ./data-service
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=${DATABASE_URL}
      - ENV=production
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    restart: unless-stopped
    depends_on:
      - postgres

  # Upload service - high resources
  upload-service:
    build: ./upload-service
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=production
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    restart: unless-stopped

volumes:
  postgres_data: