version: '3.8'

services:
  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - key-service
      - data-service
      - upload-service
    restart: unless-stopped

  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: coverage_db
      POSTGRES_USER: coverage
      POSTGRES_PASSWORD: coverage
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Key service - lightweight
  key-service:
    build: ./key-service
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    restart: unless-stopped
    depends_on:
      - postgres

  # Data service - medium resources
  data-service:
    build: ./data-service
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://coverage:coverage@postgres:5432/coverage_db
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    restart: unless-stopped
    depends_on:
      - postgres

  # Upload service - high resources
  upload-service:
    build: ./upload-service
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    restart: unless-stopped

volumes:
  postgres_data: